version: '3.4'

services:
  mediatorauthservice.api:
    container_name: mediator_authservice
    image: ${DOCKER_REGISTRY-}mediator/authserviceapi
    build:
      context: .
      dockerfile: src/Presentation/MediatorAuthService.Api/Dockerfile

  s_sqlserver:
    container_name: mediator_authservice_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest

  s_elasticsearch:
    container_name: mediator_authservice_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0 

  s_kibana:
    container_name: mediator_authservice_kibana
    image: docker.elastic.co/kibana/kibana:9.0.0